services:
  postgres:
    container_name: fresco-dev-postgres
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=postgres
    # volumes:
    #   - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", '-U', 'postgres']
      interval: 5s
      timeout: 10s
      retries: 5
    # networks:
    #   - fresco_network

# volumes:
#   postgres:
#     name: fresco-db

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
# networks:
#   fresco_network:
#     external: true
