directories:
  output: ./pkg/
appId: org.codaco.networkCanvasInterviewer7
asar: false
extraMetadata:
  name: network-canvas-interviewer
files:
  - filter:
      - ./dist-backend/**/*
      - ./dist-frontend/**/*
mac:
  category: public.app-category.education
  target:
    target: dmg
    arch:
      - x64
      - arm64
linux:
  target: appimage
electronVersion: 23.0.0
