name: Build

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SKIP_ENV_VALIDATION: true
      NEXT_PUBLIC_DISABLE_ANALYTICS: true
      DATABASE_URL: mysql://connection-string
      UPLOADTHING_SECRET: sk_live_secret
      UPLOADTHING_APP_ID: app-id
      INSTALLATION_ID: gh-action

    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run build
        run: pnpm next build
